import React from 'react'

export default function CandidateList() {
  // TODO: IF USER IS ADMIN, SHOW THE EVENT FILTER FOR CANDIDATE COMPETITIONS
  // TODO: IF USER IS ADMIN, SHOW ALL CANDIDATES FOR DIFFERENT EVENTS AND IF USER IS MANAGER SHOW ONLY THEIR CANDIDATES

  return <div>CandidateList</div>
}
