/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsEventsRouteImport } from './routes/settings.events'
import { Route as SettingsCompetitionsRouteImport } from './routes/settings.competitions'
import { Route as SettingsCandidatesRouteImport } from './routes/settings.candidates'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEventsRoute = SettingsEventsRouteImport.update({
  id: '/settings/events',
  path: '/settings/events',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCompetitionsRoute = SettingsCompetitionsRouteImport.update({
  id: '/settings/competitions',
  path: '/settings/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCandidatesRoute = SettingsCandidatesRouteImport.update({
  id: '/settings/candidates',
  path: '/settings/candidates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/settings/candidates': typeof SettingsCandidatesRoute
  '/settings/competitions': typeof SettingsCompetitionsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/settings/candidates': typeof SettingsCandidatesRoute
  '/settings/competitions': typeof SettingsCompetitionsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/settings/candidates': typeof SettingsCandidatesRoute
  '/settings/competitions': typeof SettingsCompetitionsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deferred'
    | '/login'
    | '/redirect'
    | '/unauthenticated'
    | '/unauthorized'
    | '/settings/candidates'
    | '/settings/competitions'
    | '/settings/events'
    | '/settings/users'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deferred'
    | '/login'
    | '/redirect'
    | '/unauthenticated'
    | '/unauthorized'
    | '/settings/candidates'
    | '/settings/competitions'
    | '/settings/events'
    | '/settings/users'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/deferred'
    | '/login'
    | '/redirect'
    | '/unauthenticated'
    | '/unauthorized'
    | '/settings/candidates'
    | '/settings/competitions'
    | '/settings/events'
    | '/settings/users'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeferredRoute: typeof DeferredRoute
  LoginRoute: typeof LoginRoute
  RedirectRoute: typeof RedirectRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  SettingsCandidatesRoute: typeof SettingsCandidatesRoute
  SettingsCompetitionsRoute: typeof SettingsCompetitionsRoute
  SettingsEventsRoute: typeof SettingsEventsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/events': {
      id: '/settings/events'
      path: '/settings/events'
      fullPath: '/settings/events'
      preLoaderRoute: typeof SettingsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/competitions': {
      id: '/settings/competitions'
      path: '/settings/competitions'
      fullPath: '/settings/competitions'
      preLoaderRoute: typeof SettingsCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/candidates': {
      id: '/settings/candidates'
      path: '/settings/candidates'
      fullPath: '/settings/candidates'
      preLoaderRoute: typeof SettingsCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeferredRoute: DeferredRoute,
  LoginRoute: LoginRoute,
  RedirectRoute: RedirectRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  SettingsCandidatesRoute: SettingsCandidatesRoute,
  SettingsCompetitionsRoute: SettingsCompetitionsRoute,
  SettingsEventsRoute: SettingsEventsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
