/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingPageRouteImport } from './routes/waiting-page'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsEventsRouteImport } from './routes/settings.events'
import { Route as SettingsCompetitionsRouteImport } from './routes/settings.competitions'
import { Route as SettingsCandidatesRouteImport } from './routes/settings.candidates'

const WaitingPageRoute = WaitingPageRouteImport.update({
  id: '/waiting-page',
  path: '/waiting-page',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEventsRoute = SettingsEventsRouteImport.update({
  id: '/settings/events',
  path: '/settings/events',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCompetitionsRoute = SettingsCompetitionsRouteImport.update({
  id: '/settings/competitions',
  path: '/settings/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCandidatesRoute = SettingsCandidatesRouteImport.update({
  id: '/settings/candidates',
  path: '/settings/candidates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waiting-page': typeof WaitingPageRoute
  '/settings/candidates': typeof SettingsCandidatesRoute
  '/settings/competitions': typeof SettingsCompetitionsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/users': typeof SettingsUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waiting-page': typeof WaitingPageRoute
  '/settings/candidates': typeof SettingsCandidatesRoute
  '/settings/competitions': typeof SettingsCompetitionsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/users': typeof SettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/deferred': typeof DeferredRoute
  '/login': typeof LoginRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waiting-page': typeof WaitingPageRoute
  '/settings/candidates': typeof SettingsCandidatesRoute
  '/settings/competitions': typeof SettingsCompetitionsRoute
  '/settings/events': typeof SettingsEventsRoute
  '/settings/users': typeof SettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitions'
    | '/deferred'
    | '/login'
    | '/unauthenticated'
    | '/unauthorized'
    | '/waiting-page'
    | '/settings/candidates'
    | '/settings/competitions'
    | '/settings/events'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competitions'
    | '/deferred'
    | '/login'
    | '/unauthenticated'
    | '/unauthorized'
    | '/waiting-page'
    | '/settings/candidates'
    | '/settings/competitions'
    | '/settings/events'
    | '/settings/users'
  id:
    | '__root__'
    | '/'
    | '/competitions'
    | '/deferred'
    | '/login'
    | '/unauthenticated'
    | '/unauthorized'
    | '/waiting-page'
    | '/settings/candidates'
    | '/settings/competitions'
    | '/settings/events'
    | '/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionsRoute: typeof CompetitionsRoute
  DeferredRoute: typeof DeferredRoute
  LoginRoute: typeof LoginRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  WaitingPageRoute: typeof WaitingPageRoute
  SettingsCandidatesRoute: typeof SettingsCandidatesRoute
  SettingsCompetitionsRoute: typeof SettingsCompetitionsRoute
  SettingsEventsRoute: typeof SettingsEventsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-page': {
      id: '/waiting-page'
      path: '/waiting-page'
      fullPath: '/waiting-page'
      preLoaderRoute: typeof WaitingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/events': {
      id: '/settings/events'
      path: '/settings/events'
      fullPath: '/settings/events'
      preLoaderRoute: typeof SettingsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/competitions': {
      id: '/settings/competitions'
      path: '/settings/competitions'
      fullPath: '/settings/competitions'
      preLoaderRoute: typeof SettingsCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/candidates': {
      id: '/settings/candidates'
      path: '/settings/candidates'
      fullPath: '/settings/candidates'
      preLoaderRoute: typeof SettingsCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionsRoute: CompetitionsRoute,
  DeferredRoute: DeferredRoute,
  LoginRoute: LoginRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  WaitingPageRoute: WaitingPageRoute,
  SettingsCandidatesRoute: SettingsCandidatesRoute,
  SettingsCompetitionsRoute: SettingsCompetitionsRoute,
  SettingsEventsRoute: SettingsEventsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
